trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '2e2592b3-7121-4785-80fa-c1cead082025'
  imageRepository: 'rohithmarnenimydevopsproject'
  containerRegistry: 'rohithacr2026.azurecr.io'
  dockerfilePath: 'docker/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'rohithacr202657183e98-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - script: |
        echo Build source dir: $(Build.SourcesDirectory)
        dir $(Build.SourcesDirectory)
        dir $(Build.SourcesDirectory)\frontend
      displayName: Debug - show files
      continueOnError: true

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Default
    environment: 'rohithmarneni2000mydevopsproject-1509.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)