apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohithmarnenimydevopsproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rohithmarnenimydevopsproject
  template:
    metadata:
      labels:
        app: rohithmarnenimydevopsproject
    spec:
      containers:
        - name: rohithmarnenimydevopsproject
          image: rohithacr2026.azurecr.io/rohithmarnenimydevopsproject
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralchat-secrets
                  key: OPENAI_API_KEY